name: paskerid_lmi
description: SIPKer by PASKER.ID mobile app for Android and iOS.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  pdfx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

dependency_overrides:
  pdfx:
    path: third_party/pdfx

